apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moetikeenjasaan-staging

resources:
- ../../base

# CI (promote-staging job) sets this tag automatically after dev.
images:
- name: app-image
  newName: ghcr.io/jo8s/cool-app
  newTag: b102d7013721f19661268699faec16356156b984

replicas:
- count: 1
  name: moetikeenjasaan

patches:
- patch: |-
    - op: add
      path: /spec/rules/0/host
      value: staging.localhost
  target:
    kind: Ingress
    name: moetikeenjasaan
